services:
 
  node-red:
    build: ./node-red
    ports:
      - "1880:1880"

    volumes:
    - ./node-red/workspace:/data
    environment:
    - OPENWEATHER_API_KEY=029e2971fd993ff3081a6fdf47ad6f19
